"""
Django settings for ship_well project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fev#m%cngl8++6@xmh$z)3cj-53&j9e7h@m#(@ckp9cx_3b&m@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

ROOT_URLCONF = 'ship_well.urls'

WSGI_APPLICATION = 'ship_well.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# This project uses Google Maps API with two purposes:
# 1. Translating zip codes into latitude - longitude coordinates
# 2. Checking that given latitude, longitude pair is valid
# To use that API, you must set the corresponding API KEY
# See https://developers.google.com/maps/documentation/geocoding/intro for details
GOOGLE_MAPS_API_KEY = None  # SET API KEY HERE

# By default, coordinates checking is disabled. You can enable it by setting this flag to True
ENABLE_COORDINATES_CHECKING = False
